version: "3.7"

services:
  chsystem-discord:
    container_name: chsystem-discord
    image: chsystem:latest
    networks:
      - postgres
    environment:
      DB_URI: postgresql://postgres:lPr5LSUQbgegvgw7@postgres:5432/chsystem
      DISCORD_TOKEN: MTA4MjM5MTU0ODYwOTY5MTY1OA.G3-TP9.IZt1cFdp1Jr1GZOvOBFt6Bvod20FHk5yLVxewg
      LOGTAIL_DISCORD: mVVGVu9RHR1KmLX3AHu9t4ah
    restart: always
  chsystem-notify:
    container_name: chsystem-notify
    image: chsystem:latest
    networks:
      - postgres
    environment:
      DB_URI: postgresql://postgres:lPr5LSUQbgegvgw7@postgres:5432/chsystem
      LOGTAIL_NOTIFY: 9NukbhBTmNcieJtHPhiBgM7k
    restart: always
    command: bash init.sh chsystem/notify/notify.py

networks:
  postgres:
    name: postgres
    external: true