[tool.poetry]
name = "ch-discordbot"
version = "0.2.0"
description = "ch discord bot"
authors = ["OB"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.4"
replit = "^3.0.0"
waitress = "^2.0.0"
Paste = "^3.5.0"
cutandpaste = "^0.4.0"
bs4 = "^0.0.1"
Js2Py = "^0.71"
cchardet = "^2.1.7"
nextcord = "^2.0.0-alpha.2"
aiodns = "^3.0.0"
Brotli = "^1.0.9"
orjson = "^3.6.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
