[tool.poetry]
name = "repl_python3_ch-database"
version = "0.1.0"
description = ""
authors = ["ArgoPanoptes <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
waitress = "^2.0.0"
yikai-tools = "^1.0.6"
cutandpaste = "^0.4.0"
flask = "^2.0.1"
replit = "^3.1.0"
Paste = "^3.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
