[tool.poetry]
name = "ch-discordbot"
version = "0.2.0"
description = "ch discord bot"
authors = ["OB"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.4"
replit = "^3.0.0"
discord = "^1.7.3"
waitress = "^2.0.0"
Paste = "^3.5.0"
cutandpaste = "^0.4.0"
bs4 = "^0.0.1"
Js2Py = "^0.71"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
