[tool.poetry]
name = "ch-web"
version = "0.1.0"
description = ""
authors = ["ArgoPanoptes <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
Paste = "^3.5.0"
Flask = "^2.0.1"
waitress = "^2.0.0"
requests = "^2.25.1"
replit = "^3.1.0"
cutandpaste = "^0.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
